name: Android TV CI/CD

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        cd tv-app
        npm install
        
    - name: Build Web
      run: |
        cd tv-app
        npm run build
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
        
    - name: Grant execute permission for gradlew
      run: |
        cd tv-app/android
        chmod +x gradlew
        
    - name: Build Release APK
      run: |
        cd tv-app/android
        ./gradlew assembleRelease
        
    - name: Rename APK
      run: |
        cd tv-app/android/app/build/outputs/apk/release
        mv app-release.apk mt5-candlechart-tv.apk
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: tv-app/android/app/build/outputs/apk/release/mt5-candlechart-tv.apk
        name: Release ${{ github.ref_name }}
        body: |
          MT5 K线图 Android TV应用 ${{ github.ref_name }} 版本发布
          
          ### 更新内容
          - 自动构建发布
          - 支持Android TV
          - 优化UI交互
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 