name: Android TV Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        cd tv-app
        npm install
        npm install @capacitor/cli @capacitor/core @capacitor/android
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
        
    - name: Build Debug APK
      run: |
        cd tv-app
        npx cap sync android
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug
        
    - name: Archive APK
      uses: actions/upload-artifact@v2.3.1
      with:
        name: debug-apk
        path: tv-app/android/app/build/outputs/apk/debug/*.apk 